version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "9090:80"
    volumes:
      - "pgadmin-vabf:/var/lib/pgadmin"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=orange-banbou@orange.com"
      - "PGADMIN_DEFAULT_PASSWORD=pbaq01owner"
  db:
    build:
      context: ../ressources
      dockerfile: ../ressources/Dockerfile.db.vabf.dump
    container_name: POSTGRES_DUMP_VABF
    volumes:
      - "dbdata-vabf:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  dbdata-vabf:
  pgadmin-vabf:
