discovery.zen.minimum_master_nodes: 2
discovery.zen.ping.unicast.hosts: es1, es2, es3
discovery.zen.ping_timeout: 5s
discovery.zen.commit_timeout: 5s
cluster.name: "docker-swarm-cluster"
network.host: 0.0.0.0
action.destructive_requires_name: true

#xpack.security.transport.ssl.enabled: true
xpack.license.self_generated.type: trial
xpack.security.enabled: true
xpack.monitoring.collection.enabled: true

node.attr.rack: r2