---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ "http://es1:9200" ]
#monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
#
elasticsearch.username: "kibana_system"
elasticsearch.password: "u2w1OotLpxUrbGn3gCa0"
#xpack.security.encryptionKey: "something_at_least_32_characters"
#xpack.security.session.idleTimeout: "1h"
#xpack.security.session.lifespan: "30d"
