#- pipeline.id: psql
#  path.config: "/usr/share/logstash/pipeline/logstash-psql.conf"
#  config.reload.automatic: true

- pipeline.id: tcp_beats
  path.config: "/usr/share/logstash/pipeline/logstash-beats.conf"
  config.reload.automatic: true
